### ISSUE TITLE
Support specify refresh token lifespan from login/consent application.

### ISSUE THREAD

**Issue by chaopeng** [ory/hydra#1648] opened 2019-11-25 21:28 UTC
## Issue

Currently, Hydra only supports [specifying a refresh token lifespan in the config](https://github.com/ory/fosite/blob/40a49f743dff60d07b6314667933a47dbf2635aa/compose/config.go#L35-L37). And every refresh token usage will expand the refresh token lifespan.

**Issue 1:** Identity Broker should give refresh token lifespan following upstream idps. It is also a requirement of [the RFC](https://github.com/ga4gh/data-security/blob/master/AAI/AAIConnectProfile.md#limited-damage-of-leaked-tokens).

**Issue 2:** When user choose remember information release preference (consent) for a duration, this means that the user only wants to give access for a limited time duration. The refresh token should has an expiry not longer than that.

### Solution 1 - Reuse "remember_for" in /oauth2/auth/requests/consent/accept and /oauth2/auth/requests/login/accept:

login application and consent application may call to login/accept and consent/accept endpoints with remember_for. Hydra use it to set the max_age of cookies.

We can reuse this field, pump it into fosite/Requester, save it to database in refresh token creation limit and set the expiry to shortest duration in login remember for, consent remember and refresh token lifespan.

**Cons:**
- May see unexpected behavior change when upgrade hydra, maybe make this feature behind flag.

### Solution 2 - Add new field "expiry":

Same idea with reuse "remember_for" but add a new field to prevent unexpected behavior change when upgrade hydra.

**Pros:**

- Prevent unexpected behavior change when upgrade hydra

**Cons:**

- Adding "expiry" is confused with "remember_for"

**Additional context**

### [GA4GH AAI Profile](https://github.com/ga4gh/data-security/blob/master/AAI/AAIConnectProfile.md)

This specification profiles the OpenID Connect protocol to provide a federated (multilateral) authentication and authorisation infrastructure for greater interoperability between Genomics institutions in a manner specifically applicable to (but not limited to) the sharing of restricted datasets.

### [Identity Broker](https://github.com/ga4gh/data-security/blob/master/AAI/AAIConnectProfile.md#terminology)

An OIDC Provider service that authenticates a user (potentially by an Identity Provider), collects their claims from internal and/or upstream claim sources and issues conformant JWT claims to be consumed by Claim Clearinghouses. Brokers may also be Claim Clearinghouses of other upstream Brokers (i.e. create a chain of Brokers like in the Flow of Claims diagram).

**Comment by aeneasr** [comment] 2019-11-26 09:32
This is a dupe of #1529 - please use that issue to explain why you need this feature :)

**Closed by aeneasr** 2019-11-26 09:32 UTC
