### ISSUE TITLE
Remove "not before" claim "nbf" from JWT access token

### ISSUE THREAD

**Issue by jbman** [ory/hydra#1542] opened 2019-08-21 16:19 UTC
A Hydra JWT access token contains the “not before” claim with the same value as “issued at”.
Example:
{
“exp”: 1565861736,
“iat”: 1565858136,
“nbf”: 1565858136,
…
}

This could lead to failing validations, if a resource server hasn’t the correct time set or has some seconds clock skew which but strict “not before” validation.
In addition, I think there is no point to set “nor before” to the “issued at” timestamp. This claim seems to be intended for use cases where a future date is given, so that a client can not use a token immediately (e.g. a subscription starts tomorrow and can not be used directly after token creation, see https://stackoverflow.com/questions/43291659/usage-of-nbf-in-json-web-tokens).

According to https://tools.ietf.org/html/rfc7519#section-4.1.5 the nbf claim is optional. Other implementations do not provide a “nbf” claim. Or they provide one which is set to value 0.

**Proposal**
Do not add a "nbf" claim by default. 
To create tokens which are valid in the future, the nbf value should be controlled by client configuration or login application.

**Comment by aeneasr** [comment] 2019-08-25 09:03
Thank you, I think we can have nbf optional as it really does not serve a lot of purpose.

**Comment by kanishkarj** [comment] 2020-04-25 12:43
@aeneasr Has this been addressed yet?

**Comment by aeneasr** [comment] 2020-04-25 12:45
No, the issue is still open. Contributions welcomed!

**Comment by anderslauri** [comment] 2021-03-30 20:45
> 
> 
> No, the issue is still open. Contributions welcomed!
@aeneasr, 

I would be keen on taking on this task, we're expericing issues due to clock skew issues and making `nbf` would save us some headach. I see @Benehiko is assigned this task, however, would it be in order if I were to provide a PR within the next few days?

Thank you.

**Comment by aeneasr** [comment] 2021-03-31 08:10
Yes, sounds good! I will unassign @Benehiko

**Comment by dominik-lekse** [comment] 2021-04-01 10:12
@anderslauri Thanks for taking this. We have a related issue which is fixed by your PR.

**Closed** 2021-04-04 10:51 UTC
Labels: feat, package/oauth2
