### ISSUE TITLE
Janitor does not report connection errors and ignores logging level

### ISSUE THREAD

**Issue by jay-lark** [ory/hydra#2734] opened 2021-09-09 18:55 UTC
**Describe the bug**

I haven't run into any SQL errors yet, but running the Janitor command with incorrect database credentials will give the impression that everything is working fine.

It also seems to ignore the log level set in a config file.

**Reproducing the bug**

1. Run `d./hydra janitor --requests --tokens -c hydra.yml` 

You'll get back the following
```
{"audience":"application","level":"info","msg":"No tracer configured - skipping tracing setup","service_name":"ORY Hydra","service_version":"v1.10.6","time":"2021-09-09T18:47:07Z"}
Successfully completed Janitor run on access tokens
Successfully completed Janitor run on refresh tokens
Successfully completed Janitor run on login-consent requests
```

In the above example my `hydra.yml` file had incorrect login credentials for my database server.  I had also set the log level to debug.

I know the config file is correct because if I do put the correct credentials in, my database tables are pruned.

**Expected behavior**

Some error message indicating a connection error

**Environment**

- Version: v1.10.6, git sha f1771f13dd954b37330d4e90d89df41fc40be460
- Environment: Ubuntu 20.0.4, AWS MySQL RDS cluster

**Comment by aeneasr** [comment] 2021-09-10 05:42
That looks indeed like a bug - any contributions towards fixing that are highly appreciated!

**Comment by Benehiko** [comment] 2021-09-16 13:25
I will take a look at fixing this

**Comment by Benehiko** [comment] 2021-09-16 16:27
Some more information after debugging this for a while. I traced the error to `gobuffalo/pop` not throwing an error on PostgreSQL and MySQL. This doesn't happen with CockroachDB since it runs the `AfterOpen` command which executes a transaction against the database for additional information about the database. See [gobuffalo/pop connection.go](https://github.com/gobuffalo/pop/blob/33f2d5c4a214cb81adeaf4f8a84662dec29226b1/connection.go#L129-L134)

When `Janitor` runs it opens the connection through `gobuffalo/pop` through the `driver.Init()` command, but it doesn't throw any error and then continues running the cleanup commands inside a transaction.

See [handler_janitor.go](https://github.com/ory/hydra/blob/6ea0bf8f4dc990667c6911c92a1ad644733745be/cmd/cli/handler_janitor.go#L120-L123)
```go
if err := d.Init(cmd.Context()); err != nil {
    return fmt.Errorf("%s\n%s\n", cmd.UsageString(),
              "Janitor can only be executed against a SQL-compatible driver but DSN is not a SQL source.")
}
```

The transaction doesn't check for all errors and only if the error matches exactly `sql.ErrNoRows` which it doesn't when there is no connection to the host as seen in [persister_oauth2.go](https://github.com/ory/hydra/blob/6ea0bf8f4dc990667c6911c92a1ad644733745be/persistence/sql/persister_oauth2.go#L375-L382)

```go
q := p.Connection(ctx).RawQuery(
    fmt.Sprintf("SELECT signature FROM %s WHERE requested_at < ? ORDER BY signature LIMIT %d",
	OAuth2RequestSQL{Table: sqlTableAccess}.TableName(), limit), notAfter,
)
	
if err := q.All(&signatures); err == sql.ErrNoRows {
    return errors.Wrap(fosite.ErrNotFound, "")
}
```

**Comment by Benehiko** [comment] 2022-04-22 17:18
Basically we need to do a `db.Ping` after `init` and before the transactions happen to force an open connection and then output the correct error logs.

**Comment by ludydoo** [comment] 2022-04-23 06:47
@jay-lark @Benehiko I could not reproduce. 

Am I missing something?

1. spin up hydra + hydra-migrate + mysql
```
docker-compose -f quickstart.yaml -f quickstart-mysql.yaml up - d
```
2. run `janitor` 
```
DSN="mysql://root:WRONG@tcp(mysqld:3306)/mysql?max_conns=20&max_idle_conns=4" go run . janitor --requests --tokens -e
```

3. also tried with a config file instead of env var
```
#hack.yaml
dsn: mysql://root:WRONG@tcp(localhost:3306)/mysql?max_conns=20&max_idle_conns=4

go run . janitor --requests --tokens -c hack.yaml 
```
Gives 

```
INFO[2022-04-23T08:34:21+02:00] No tracer configured - skipping tracing setup  audience=application service_name=Ory Hydra service_version=master
Error: Could not cleanup inactive access tokens: unable to fetch records: mysql select many: Error 1045: Access denied for user 'root'@'172.18.0.1' (using password: YES)
[...]
Could not cleanup inactive access tokens: unable to fetch records: mysql select many: Error 1045: Access denied for user 'root'@'172.18.0.1' (using password: YES)
exit status 255
```

**Comment by Benehiko** [comment] 2022-04-23 07:17
Ah nice, then it was probably fixed some while ago with another issue. Could you maybe check what changed between then and now on the driver.Init maybe or the Janitor itself?

**Comment by Benehiko** [comment] 2022-04-23 07:18
It is also possible that pop was updated and now automatically does an "AfterOpened" call. Previously it would only do that for CockroachDB.

**Comment by ludydoo** [comment] 2022-04-23 07:41
@Benehiko the fix has been made by "mitar" on Nov 22nd 2121 on commit 33d75d791d801b5bbb2ece442c7e2836fce3a657. 

```
if err := q.All(&signatures); err == sql.ErrNoRows {
  return errorsx.WithStack(fosite.ErrNotFound)
} else if err != nil {
  return errorsx.WithStack(err)
}
```

I don't think that the connection is tested `AfterOpen` in all cases. The error says `unable to fetch records`. Seems that the reason that this bug was not apparent for CockroachDB is perhaps only due to pop testing the connection afteropen for that specific database.

**Comment by Benehiko** [comment] 2022-04-23 07:45
Thank you @ludydoo for taking a look :)

Seems like we can close this issue then

**Comment by zepatrik** [comment] 2022-04-23 10:39
I would still like to fix the init function to do a ping. We do it in Kratos and Keto, so it would be good to test the connection right at the startup. Then we also have it in a backoff retry, in case the DB needs some time to come alive (mysql).

**Comment by ludydoo** [comment] 2022-04-27 07:12
@zepatrik @aeneasr after some investigation, `pop`'s `Ping` function actually doesn't do anything. Seems broken to me. Unless this is intended behavior, but that seems unlikely.

I've tried with this:

```
if err := d.Ping(); err != nil {
return fmt.Errorf("%s\n%s\n%s\n", cmd.UsageString(),
	err.Error(),
	"There was an error connecting to the database. Please check your DSN.")
}
```
I've tracked it down to https://github.com/gobuffalo/pop/blob/7c4104dcfcc2940ecb9625135c49063e609fe05f/connection.go#L102-L139

`d.Ping()` internally calls `connection.Open()`. This method immediately returns without an error if the `connection.Store != nil`. Which is always `true` as soon as we create the driver with `d = driver.New(cmd.Context(), do...)`

So adding a `Ping` at this stage unfortunately does nothing. The janitor will still fail as soon as a query is attempted.

**Comment by ludydoo** [comment] 2022-04-27 07:21
Upgrading to `gobufallo/pop` v6.0.2 doesn't help

**Comment by ludydoo** [comment] 2022-04-27 07:27
On another note, it seems the call to `d.Init()` is superfluous

```
if err := d.Init(cmd.Context()); err != nil {
return fmt.Errorf("%s\n%s\n", cmd.UsageString(),
	"Janitor can only be executed against a SQL-compatible driver but DSN is not a SQL source.")
}
```
it is already called in `driver/factory.go`

**Comment by Benehiko** [comment] 2022-04-27 09:58
Hi @ludydoo 

Yes you are correct, it seems the driver is already initialized in `driver/factory.go`.  We can then remove the init here in janitor. I was also looking into the `Ping()` issue a bit - to me it seems what is happening is we reuse the `Ping()` function from the golang `database/sql` library. 

```go
// Ping verifies a connection to the database is still alive,
// establishing a connection if necessary.
//
// Ping uses context.Background internally; to specify the context, use
// PingContext.
func (db *DB) Ping() error {
	return db.PingContext(context.Background())
}
```

Going into the code a bit it seems that `pop` has a `dB` struct which embeds `sqlx.DB`

```go
type dB struct {
	*sqlx.DB
}
```

In `pop` the `connection.Open()` function creates a new `dB` object and stores it inside the `c.Store` variable 

```go
// Connection represents all necessary details to talk with a datastore
type Connection struct {
	ID          string
	Store       store
	Dialect     dialect
	Elapsed     int64
	TX          *Tx
	eager       bool
	eagerFields []string
}

// Open creates a new datasource connection
func (c *Connection) Open() error {
	if c.Store != nil {
		return nil
	}
	if c.Dialect == nil {
		return errors.New("invalid connection instance")
	}
	details := c.Dialect.Details()

	db, err := openPotentiallyInstrumentedConnection(c.Dialect, c.Dialect.URL())
	if err != nil {
		return err
	}

	db.SetMaxOpenConns(details.Pool)
	if details.IdlePool != 0 {
		db.SetMaxIdleConns(details.IdlePool)
	}
	if details.ConnMaxLifetime > 0 {
		db.SetConnMaxLifetime(details.ConnMaxLifetime)
	}
	if details.ConnMaxIdleTime > 0 {
		db.SetConnMaxIdleTime(details.ConnMaxIdleTime)
	}
	if details.Unsafe {
		db = db.Unsafe()
	}
	c.Store = &dB{db}

	if d, ok := c.Dialect.(afterOpenable); ok {
		if err := d.AfterOpen(c); err != nil {
			c.Store = nil
			return fmt.Errorf("could not open database connection: %w", err)
		}
	}
	return nil
}
```

We then have a struct called `Persister` which contains `pop.Connection` which exposes the `Store` object which we use to do call the `Ping()` function. I'm using Kratos here as an example since in Hydra we have not implemented this.

https://github.com/ory/kratos/blob/e4f205d69bec07a71bf1d34d97ab3a6b99a4cc46/persistence/sql/persister.go#L42-L50

But to do that we need to tell go that it does implement the `Ping()` function (which it does but actually through the `dB` struct a few layers deep. `dB` -> `sqlx.DB` -> `sql.DB` -> `Ping()`
```go
type dB struct {
	*sqlx.DB
}```

We can then call the `Ping` function like so:

```go
c.Store.(interface{ Ping() error }).Ping()
```

**Comment by Benehiko** [comment] 2022-04-27 10:01
This issue is then technically not a `Janitor` issue. It's more a `driver` issue (where we init and open the connection`. I think this is quite a deep topic since it goes very deep into pop and our connection code - more so than I or @zepatrik realised :p 

I think this would be enough work to fix this in a PR and then we can be certain this issue is also fixed properly :)

**Closed** 2022-05-18 06:46 UTC
Labels: taken
