### ISSUE TITLE
Which version is stable?

### ISSUE THREAD

**Issue by JamesnaW** [ory/hydra#922] opened 2018-07-12 03:21 UTC
I looking in guide on branch latest(stable) version you recommend `oryd/hydra:v1.0.0-beta.6` but on master(unstable) recommend `oryd/hydra:v1.0.0-beta.5`. So is v1.0.0 ready to use on production?

**Comment by arekkas** [comment] 2018-07-12 09:06
There are various aspects to calling something "ready for production". We have extensive qa/test suites that make sure that each release is safe to run in the wild. Any release, be it `beta` or `rc` is ok to run facing the public net. The `beta` flag refers to the software not having (a) the full feature set yet and (b) warning you that upgrading from each beta version to the next might introduce minor or major breaking changes.

We generally recommend going with 1.0.0 release as you will need to do a lot of work to get from 0.11 to 1.0. And there, always go with the latest release. The mismatch of versions on the branches might be caused by some CI pipeline failing.

**Comment by arekkas** [comment] 2018-07-14 13:12
Closing, because I believe the question is answered

**Closed by arekkas** 2018-07-14 13:12 UTC
