### ISSUE TITLE
Go sdk as a separate go module

### ISSUE THREAD

**Issue by danielvladco** [ory/hydra#1497] opened 2019-07-19 14:34 UTC
**Is your feature request related to a problem? Please describe.**
When I want to use the hydra SDK in my project I use the command 
`go get github.com/ory/hydra@v1.0.0`
however when using go modules it downloads all other go source files that are not required for the SDK and adds a lot of unneeded dependencies to the project.

If I use the command 
`go get -u -d github.com/ory/hydra/sdk/go/hydra/...`
I receive this message:
```sh
go: finding github.com/ory/hydra/sdk/go/hydra/... latest
go: finding github.com/ory/hydra/sdk/go/hydra latest
go: finding github.com/ory/hydra/sdk/go latest
go: finding github.com/ory/hydra/sdk latest
go get github.com/ory/hydra/sdk/go/hydra/...: no matching versions for query "latest"
```

**Describe the solution you'd like**
The most appropriate solution I think will be to make /sdk/go/hydra a separate go module within the same repository

**Describe alternatives you've considered**

Create separate repositories for each client

**Additional context**
This is my current directory structure for the dependencies. As you can see there is all the source code for the hydra.

![image](https://user-images.githubusercontent.com/22772954/61543025-582b1b80-aa4b-11e9-8228-f1841a36901e.png)

**Comment by aeneasr** [comment] 2019-07-23 08:58
Hey! Thanks for creating the issue - this is a dupe of #1422 where we also explain why a separate module will be somewhat tricky for our deployment pipeline and some ideas how to resolve this hopefully (e.g. GOPROXY).

**Comment by aeneasr** [comment] 2019-07-23 08:58
(closing this as dupe, feel free to comment and I'll reopen)

**Closed by aeneasr** 2019-07-23 08:58 UTC
