### ISSUE TITLE
JSON Web Key Store default keys broken after upgrading to beta.6

### ISSUE THREAD

**Issue by Entrio** [ory/hydra#921] opened 2018-07-12 03:07 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Hydra does not startup

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Perform a migration from b4->b6

**What is the expected behavior?**
Hydra should startup )

**Which version of the software is affected?**
hydra b6

In the error log I get the following error:

time="2018-07-12T09:04:49+06:00" level=fatal msg="Unable to refresh OpenID Connect signing keys." error="public and private key pair kids do not match"

**Comment by arekkas** [comment] 2018-07-12 09:02
I think the issue is that the new generator expects the keys from the JSON Web Key storage to have matching public/private kids. Can you sign into the db and run:

```
DELETE FROM hydra_jwk WHERE sid='hydra.https-tls' OR sid='hydra.openid.id-token'
```

**Comment by Entrio** [comment] 2018-07-12 09:23
After performing those queries, hydra generated new keys but my client now fails to authenticate with the following error:
Client supports client authentication method \"client_secret_basic\", but method \"client_secret_post\" was requested.

**Comment by Entrio** [comment] 2018-07-12 10:06
For those like me, the issue was that I needed to update the property of the client in hydra.
Using standard PUT method, change "token_endpoint_auth_method": "client_secret_post"

I think this issue can now be considered closed

**Comment by arekkas** [comment] 2018-07-12 10:16
The original issue will be fixed by hydra re-generating the keys if the format is broken

**Closed** 2018-07-15 11:44 UTC
