### ISSUE TITLE
Invalid expiration time during introspection the token refresh

### ISSUE THREAD

**Issue by pr0head** [ory/hydra#1296] opened 2019-03-04 20:32 UTC
**Describe the bug**
Introspection of refresh token returns incorrect expiration time. The expiration time is the same as the access token expiration time.

**To Reproduce**
1. Download latest version from GitHub
2. Add to the docker-compose.yml environment variable: `- REFRESH_TOKEN_LIFESPAN=720h`
3. Run `docker-compose -p hydra -f docker-compose.yml up --build`
4. Log in and get the code to exchange tokens
5. Exchange code for tokens
6. Send a refresh token to the endpoint of introspection
7. Received token has an expiration time of 1 hour (default value for access tokens)

**Expected behavior**
The expiration time should be 720 hours, as specified by the configuration parameter.

**Version:**
 - Environment: Docker Desktop 2.0.0.3 (31259), Kubernetes 1.10.11
 - Version: master

**Comment by aeneasr** [comment] 2019-03-04 20:51
What does `git rev-parse HEAD` say?

**Comment by pr0head** [comment] 2019-03-04 20:52
1295663ada908dd431d7ffc9927feb6e2606b724

**Comment by aeneasr** [comment] 2019-03-04 20:56
Your master is way behind, please try with a recent version...

**Comment by pr0head** [comment] 2019-03-04 21:10
I updated to the latest version of the wizard - c174f96e6e8ab31aa362c7a5d32e5637984aab5b, but the problem has not been fixed

**Comment by aeneasr** [comment] 2019-03-04 21:11
Could you provide appropriate CURL commands for easier debugging? Also, does this affect only the response of token introspection?

**Comment by pr0head** [comment] 2019-03-04 21:17
> Also, does this affect only the response of token introspection?
Yes, the expiration time for the access token is returned correctly. When the ACCESS_TOKEN_LIFESPAN parameter is changed, the expiration time also changes correctly.

```
curl -X POST \
  http://192.168.5.12:4445/oauth2/introspect \
  -H 'Postman-Token: 50e3be92-4917-4fc7-ae68-d789e82f17fc' \
  -H 'cache-control: no-cache' \
  -d 'token=0KuBIL84xrL0cy72OcuWP_sVu8e3NzJ4447-ziwEadk.eUGZskTbVlWl_U_NQjjP00ScOz_K_ehgrn3PTvOHQTs&undefined='
{"active":true,"scope":"openid offline","client_id":"5c7d930a02429c10c0864511","sub":"5c7d934002429c10c0864513","exp":1551744293,"iat":1551733492,"iss":"http://192.168.5.12:4444/","token_type":"refresh_token"}
```

**Comment by aaslamin** [comment] 2019-03-04 22:05
I think this may be a bug/oversight @aeneasr - the response only returns the expiration of the access token:

https://github.com/ory/hydra/blob/master/oauth2/handler.go#L435

Instead I believe it should examine the token type and return the correct expiry based on the type of the token being introspected.

Yea?

**Comment by aeneasr** [comment] 2019-03-05 07:47
Yeah that seems to be the cause here! Anyone up for a PR?

**Comment by aaslamin** [comment] 2019-03-05 19:22
Feel free to assign this to me unless @pr0head wants to take it on.

I will dish out some time for this in coming weeks.

**Comment by pr0head** [comment] 2019-03-05 20:36
@aaslamin I'll try )

**Closed** 2019-03-17 17:14 UTC
