### ISSUE TITLE
Device Authorization Grant

### ISSUE THREAD

**Issue by Renkas** [ory/hydra#1553] opened 2019-09-03 22:41 UTC
Have you concidered adding support of Device Authorization Grant?
Also known as Device Code grant.

[RFC8628 Device Authorization Grant](https://tools.ietf.org/html/rfc8628)

**Comment by aeneasr** [comment] 2019-09-14 15:32
Yes, I think adding this grant would make sense. It would however require another endpoint at the login/consent app. We're currently in feature freeze mode for Hydra as we're working on other projects but if you're up for a PR we would happily accept it.

Please be aware that this will be significant a amount of work so please discuss your ideas for implementing it with us beforehand. Another option is to become a sponsor which allows us to allocate more resources towards requests like this.

**Comment by Renkas** [comment] 2019-09-16 14:43
I would be useless on developing it. But we have a usecase where we need to use this grant type soon so it would be nice to have all the grant types in one package.

But if there's no plans to add it soon then I think we need to find another solution right now. But hopefully it will make its way to Hydra so we can switch to it in future.

**Comment by aeneasr** [comment] 2019-09-16 20:15
Ok, as said in the previous post we do not have capacities or resources to add additional grant types right now.

**Comment by rickwang7712** [comment] 2020-06-11 01:58
I’m also looking forward to this feature to come true in Hydra...
We have a use case for authentication on Linux PC with only console interface, 
although this requirement is fulfilled by using another OP...

**Comment by AndreasGB** [comment] 2020-06-16 11:57
I also have a use case where it would be useful to me, but also don't have the right skill-set to implement it :/

**Comment by Jameclarke** [comment] 2020-06-16 16:03
Does anyone know what is involved in a sponsorship, that @aeneasr was mentioning?
It would be great for an update thanks everyone for gaining some traction.

**Comment by AndreasGB** [comment] 2020-06-16 16:37
I understand that as paying them to implement it

**Comment by Jameclarke** [comment] 2020-06-18 00:58
How much do you think that would be?

**Comment by AndreasGB** [comment] 2020-06-18 08:44
That's something you should probably discuss with the developers via mail. Any number I could tell you would at best be an uninformed guess.

**Comment by aeneasr** [comment] 2020-06-18 10:08
Hi there! For all open source support licenses head over to: https://github.com/ory/open-source-support

We're currently very busy with github.com/ory/kratos and some other projects which is why we simply don't have the resources right now to work on this (also because it is a big change). Support contracts help us increase our budget, hire more developers, and work on all the amazing stuff the community comes up with :)

**Comment by aeneasr** [comment] 2021-09-21 05:43
Marked as stale in error.

**Comment by vinckr** [comment] 2022-02-07 16:53
Duplicate of https://github.com/ory/hydra/issues/2416. 
Please refer to https://github.com/ory/hydra/issues/2416 for further discussion, there is also a more detailed proposal for implementation in that issue.

**Closed by vinckr** 2022-02-07 16:53 UTC
Labels: feat, help wanted, package/oauth2, rfc
