### ISSUE TITLE
Fix import path for logrus

### ISSUE THREAD

**Issue by hannson** [ory/hydra#477] opened 2017-06-02 01:35 UTC
Due to a change in the import path of the logrus package I cannot `go get` hydra or build it on OS X. This is likely to be the case until hydra and all its dependencies start using the correct import path for logrus: "github.com/sirupsen/logrus"

> ➜  idp git:(master) ✗ go get -d -u github.com/ory/hydra
package github.com/ory/hydra/cmd/server: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

From the package README: 

> The organization's name was changed to lower-case--and this will not be changed back. If you are getting import conflicts due to case sensitivity, please use the lower-case import: github.com/sirupsen/logrus.

Files in hydra containing the wrong import path:
```
./compose/firewall.go:	"github.com/Sirupsen/logrus"
./config/backend_connections.go:	"github.com/Sirupsen/logrus"
./config/backend_connections_test.go:	"github.com/Sirupsen/logrus"
./config/config.go:	"github.com/Sirupsen/logrus"
./docs/api.swagger.yaml:    x-go-package: github.com/ory/hydra/vendor/github.com/Sirupsen/logrus
./glide.lock:- name: github.com/Sirupsen/logrus
./glide.yaml:- package: github.com/Sirupsen/logrus
./integration/sql_schema_test.go:	"github.com/Sirupsen/logrus"
./oauth2/fosite_store_sql.go:	"github.com/Sirupsen/logrus"
./oauth2/fosite_store_test.go:	"github.com/Sirupsen/logrus"
./oauth2/handler.go:	"github.com/Sirupsen/logrus"
./oauth2/handler_consent_test.go:	"github.com/Sirupsen/logrus"
./oauth2/introspector_test.go:	"github.com/Sirupsen/logrus"
./oauth2/revocator_test.go:	"github.com/Sirupsen/logrus"
./pkg/errors.go:	log "github.com/Sirupsen/logrus"
./pkg/retry.go:	"github.com/Sirupsen/logrus"
./warden/warden_local.go:	"github.com/Sirupsen/logrus"
./warden/warden_test.go:	"github.com/Sirupsen/logrus"
```

**Comment by arekkas** [comment] 2017-06-04 11:23
This is invalid, see the readme:

> Seeing weird case-sensitive problems? See this issue. This change has been reverted. I apologize for causing this. I greatly underestimated the impact this would have. Logrus strives for stability and backwards compatibility and failed to provide that.

**Comment by arekkas** [comment] 2017-06-04 11:25
Sorry, I didn't want to close it, just saying that this isn't caused by hydra but probably by some dependency.

**Comment by arekkas** [comment] 2017-06-04 11:50
Ok, apparently this is simply a huge mess, the naming has been lower-cased, then renamed and is back to lower case again, basically breaking any dependency. The only way to circumvent this for now is to download hydra in the right directory (e.g. via git clone) and then run glide install.

Sorry for the inconvenience, but this is not on our plate, see #451 .

**Comment by arekkas** [comment] 2017-06-05 06:00
I checked if this actually prevents downloading hydra - it doesn't. So it's just a warning that you can ignore.

**Comment by arekkas** [comment] 2017-06-05 06:03
I've added a note on this to the readme.

**Comment by arekkas** [comment] 2017-07-07 20:52
This is resolved now

**Closed by arekkas** 2017-07-07 20:52 UTC
Labels: bug, other, upstream
