### ISSUE TITLE
Cannot revoke token from administrative API.

### ISSUE THREAD

**Issue by Amartel1986** [ory/hydra#1913] opened 2020-06-17 14:02 UTC
My final goal is to create a one-time token that will be dropped as soon as it is used for the first time for a specific action. In order to do this I've created a new endpoint in my application that calls token introspection. Once the token is validated, if it was qualified as a one-time, it should be revoked. Unfortunately, right now it can be revoked only from public API and only by the client this token was generated for.

I believe this feature may be useful not only in my case, but also for any management application that may want to drop a compromised token, for example.

**Comment by aeneasr** [comment] 2020-06-18 10:06
Please keep in mind that OAuth2 is not a TOTP mechanism. Revoking an access token immediately after use is not the intention of OAuth2, which is a protocol for delegating authorization to a third party. Using OAuth2 tokens for TOTP mechanisms is like using a browser cookie for persistent storage.

Having said that I can see the value of revoking an access token from the administrative API, without owning the client (e.g. on misuse). However, this feature is already implemented, but differently - when token misuse is detected, the client is seen as compromised and we mistrust it. This can be done via this API: https://www.ory.sh/hydra/docs/reference/api#revokes-consent-sessions-of-a-subject-for-a-specific-oauth-20-client

The idea behind token revokation itself is that a client indicates to the authorization server that it no longer needs the token, hence it is being revoked!

**Comment by Amartel1986** [comment] 2020-06-18 12:00
Thanks for the answer.

I do understand that this is not the perfect approach for verifying the user's identity. We've decided to borrow this flow from Auth0 where it is the only way to ask the user to pass a MFA in order to perform a single secure task.

I do also understand that MFA is not a part of the standard and theoretically should be distinguished from the auth provider, however in practice with most auth providers it is a part of their flow and cannot be passed separately from it.

Unfortunately revoking consent sessions is not the solution for me since it cannot revoke a specific session and revokes all of the user's sessions which forces the user to pass MFA once again for all of his sessions.

**Comment by aeneasr** [comment] 2020-06-18 14:16
I see - yeah Auth0 is known for doing "let's use OAuth2 to solve a completely different use case" ;)

I do see some value in being able to revoke tokens on the admin side without knowing the client so it might end up here after all. If you do want MFA and all of that jazz, maybe give github.com/ory/kratos a try! We haven't implemented all the flows yet but it's all on the roadmap!

**Comment by aeneasr** [comment] 2020-07-01 19:48
Dupe of #1728

**Closed by aeneasr** 2020-07-01 19:48 UTC
