### ISSUE TITLE
No way to revoke all refresh and access tokens for a subject

### ISSUE THREAD

**Issue by piyush-banknovo** [ory/hydra#1550] opened 2019-09-02 11:53 UTC
I want to revoke all the access/refresh tokens for the subject. I came across the following api:
DELETE /oauth2/auth/sessions/consent?subject=string HTTP/1.1, 

but it does not delete refresh token. Is there any way to remove refresh token as well?

**Comment by aeneasr** [comment] 2019-09-14 15:34
This should deinifitely delete the refresh token and is also (to my knowledge) well tested. Are you sure the token was not removed and if so, could you please provide a reproducible case so we can fix it?

**Comment by aeneasr** [comment] 2019-09-16 09:39
For clarification, the refresh token chain needs to be kept alive because one can also revoke older refresh tokens. If a refresh token is still active (ie TTL not expired) it can not be removed.

Also closing because reply pending for 14 days and no additional info was given and also no issue template used.

**Closed by aeneasr** 2019-09-16 09:39 UTC

**Comment by henrypham299** [comment] 2021-07-12 14:03
@aeneasr  How about the case the user reset the password? and we want to expire all the accessToken and refresh token? Should we provide a way to expire all the access token and refresh token?
