### ISSUE TITLE
localhost https bug x-forward-proto is back

### ISSUE THREAD

**Issue by aaahrens** [ory/hydra#1265] opened 2019-01-19 20:18 UTC
**Describe the bug**
Even if localhost is whitelisted https termination is not disabled

outputs: 
**To Reproduce**
> HTTPS_ALLOW_TERMINATION_FROM=127.0.0.0/32,::1/32 DATABASE_URL=memory OAUTH2_ISSUER_URL=https://localhost/accounts ~/bin/hydra serve all

input: 
> wget 127.0.0.1:4445/clients

outputs:
> WARN[0018] Could not serve http connection   error="X-Forwarded-Proto header is missing"

**Expected behavior**

Https termination

**Version:**

Version:    v1.0.0-rc.6+oryOS.10
Git Hash:   bdb6634e3d870918b0914f4210d95ae1872e2f51
Build Time: 2018-12-21T17:00:54Z

On a laptop, but prod is in k8

**Comment by aeneasr** [comment] 2019-01-20 12:15
Not a bug, `wget 127.0.0.1:4445/clients` is missing the `X-Forwarded-Proto: https` header.

**Comment by aeneasr** [comment] 2019-01-23 09:06
Closing, feel free to reopen/comment if I'm mistaken.

**Closed by aeneasr** 2019-01-23 09:06 UTC
