### ISSUE TITLE
`handled_at` in `acceptConsentRequest` does not used 

### ISSUE THREAD

**Issue by chaopeng** [ory/hydra#1834] opened 2020-04-30 01:01 UTC
**Describe the bug**

In `/oauth2/auth/requests/consent/accept`: `acceptConsentRequest` includes [`handled_at`](https://github.com/ory/hydra/blob/eca9b2d83702cd541e838b54f53b09f6c5a985ef/consent/types.go#L154) field, but it does not use in [handler](https://github.com/ory/hydra/blob/eca9b2d83702cd541e838b54f53b09f6c5a985ef/consent/handler.go#L559)

It think it make sense to gen the timestamp in hydra. I am just thinking `handled_at` in `acceptConsentRequest` will be confusing. We can either remove `handled_at` in `acceptConsentRequest` or handle `handled_at` if it is not null.

**Comment by aeneasr** [comment] 2020-05-01 11:39
Right, so you mean that the value is being set twice, which is unnecessary? Or are you experience a bug?

**Comment by chaopeng** [comment] 2020-05-01 15:00
I am not experience a bug. It is just unnecessary and confusing to me. Does it need to give the handled_at in acceptConsentRequest so I can get the handled_at in list consent session. Then I have to confirm in source.

**Comment by aeneasr** [comment] 2020-05-02 15:53
Right! Sometimes a bit of duplication is ok because it makes regressions less likely and is more resiliant :) I'll be closing this as a nofix!

**Closed by aeneasr** 2020-05-02 15:53 UTC
