### ISSUE TITLE
consent_challenge should be able to skip supplying session_data if consent marked skip

### ISSUE THREAD

**Issue by ghenry** [ory/hydra#1861] opened 2020-05-18 12:04 UTC
As per:

https://community.ory.sh/t/user-consent-and-skip-with-id-token-and-access-token-session-data-always-needed/1743

```
Hi all,

I’m just cleaning up what I’ve done in OAuth 2.0 Authorize Code Flow + PCKE + AppAuth success. Thank you! and have an issue once a user has logged in and given consent (well, for a first-class app, consent is automatic in this example).

So my flow, as per the example Login and Consent app is working correctly for the first login and auto-consent, but the second time I do it I have an issue (it’s within the session length I set in login and consent of 3600s each).

Let me explain. User logs in and a session is created in our Login and Consent App. Consent challenge comes in after this, so I have a session cookie so I know who logged in. I want to know because I set things in the access_token and id_token session data that I PUT back to Hydra.

Once I have PUT the consent, I delete the session. The next time the user comes in, Login and Consent are marked skip, so no session is created between the two in our server, so I don’t know who the user is to PUT back exactly like I did the first time.

I think I shouldn’t have to add in the session data again in the next consent acceptance if it’s marked SKIP as I don’t have it.

Make sense? What are others doing there? Whether login or consent are marked SKIP or not, we seem to have to alway supply the same data in the consent acceptance which feels wrong to me. I know the subject, but without creating an authenticated session our side again, I don’t have access to all the user info that I want.

Does it get overwritten each time?

Thanks,
Gavin.
```

**Comment by ghenry** [comment] 2020-05-19 00:00
I’m not actually ever seeing consent being marked as skip.

**Comment by aeneasr** [comment] 2020-05-19 06:19
> I’m not actually ever seeing consent being marked as skip.

This works and the cause for not seing a consent marked as skipped has to do with your workflow. E.g. not accepting all scopes, using a different OAuth2 client, forgetting to set remember: true.

**Comment by ghenry** [comment] 2020-05-19 08:26
On Tue, 19 May 2020, 07:19 hackerman, <notifications@github.com> wrote:

> I’m not actually ever seeing consent being marked as skip.
>
> This works and the cause for not seing a consent marked as skipped has to
> do with your workflow. E.g. not accepting all scopes, using a different
> OAuth2 client, forgetting to set remember: true.
>

Thanks. Where can I read the exact reasons? I'm pretty sure I'm doing all
those. Or is there a log/debug level that shows this?

Gavin.

>

**Comment by ghenry** [comment] 2020-05-19 09:59
@aeneasr 

Would this be happening because I'm using AppAuth and the code_verifier always changes etc.? So Consent will never be skipped? Client ID is the same on the mobile app.
I'm returning the same scopes that come back from Hydra when I query the consent_challenge.
Thanks.

**Comment by aeneasr** [comment] 2020-05-25 08:10
Consent is skipped for public clients (ones that do not have a secret) when the Redirect URI scheme is not `https` but instead a custom redirect scheme. Reasoning is that Eva (evil actor) can re-run the flow, set up her own endpoint at the custom redirect, request the user to consent, and the user consents without UI interception, thus exposing tokens.

**Closed by aeneasr** 2020-05-25 08:10 UTC
Labels: enhancement

**Comment by ghenry** [comment] 2020-05-25 08:55
Thanks. That's what I have, a custom scheme using AppAuth. Yesterday we spoke about this and https schemes seem to preferred when using AppAuth. I think this should remain open. There's something not right here. 

Probably my side, the client I have registered uses a custom scheme.

Thanks.
