### ISSUE TITLE
Warden API docs do not talk about access_token

### ISSUE THREAD

**Issue by mozbhearsum** [ory/hydra#564] opened 2017-07-28 14:25 UTC
Eg: http://docs.hydra13.apiary.io/#reference/warden/wardengroups/find-group-ids-by-member

With some help, I discovered that I need to pass an access_token when making requests to Warden endpoints. This isn't currently documented.

**Comment by arekkas** [comment] 2017-07-29 08:09
Dupe of #565

**Closed by arekkas** 2017-07-29 08:09 UTC
