### ISSUE TITLE
How to store my access token in the browser storage?

### ISSUE THREAD

**Issue by KishanRavindran** [ory/hydra#1286] opened 2019-02-15 10:49 UTC
Hi all,
I am using the ORY hydra for authentication and authorization. I followed the exact steps as in ory hydra login-consent from node. I got a redirect URL from backend which is giving me access token I want to store it in my browser storage so that I can use to authenticate the API which is called from browser end. I use docker hydra I run the server

```
docker run -it --rm --name dream-app-login -p 4444:4444 -p 4445:4445 \
    -e OAUTH2_SHARE_ERROR_DEBUG=1 \
    -e LOG_LEVEL=debug \
    -e OAUTH2_CONSENT_URL=http://localhost:4200/consent \
    -e OAUTH2_LOGIN_URL=http://localhost:4200/login \
    -e OAUTH2_ISSUER_URL=http://localhost:4444 \
    -e DATABASE_URL=memory \
    -e CORS_ALLOWED_ORIGINS=* \
    oryd/hydra:v1.0.0-beta.9 serve all --dangerous-force-http
```
Where the login and consent URL is my front end URL.
Next, I created client

```
docker run --link dream-app-login:hydra oryd/hydra:v1.0.0-beta.9 clients create \
    --endpoint http://hydra:4445 \
    --id test-client \
    --secret test-secret \
    --response-types code,id_token \
    --grant-types refresh_token,authorization_code \
    --scope openid,offline \
    --callbacks http://127.0.0.1:4446/callback
```
In the above i want to change the callback url to my front end url which is localhost:4200 but when i tried the application was not running.

And now running the authorization grant flow with this

```
docker run -p 4446:4446 --link dream-app-login:hydra oryd/hydra:v1.0.0-beta.9 token user \
    --token-url http://hydra:4444/oauth2/token \
    --auth-url http://localhost:4444/oauth2/auth \
    --scope openid,offline \
    --client-id test-client \
    --client-secret test-secret 
```
After this, I open the browser and did the login and consent flow and got the tokens but I want to store them in my browser storage like session storage or local storage. So is there any way to do that.

**Comment by aeneasr** [comment] 2019-02-15 10:54
If you have the tokens, you can store them in the session storage. How you implement that is totally up to you. This doesn't have to do anything with hydra itself (it's not a bug, not a feature request) -> closing.

**Closed by aeneasr** 2019-02-15 10:54 UTC

**Comment by aeneasr** [comment] 2019-02-15 10:56
Seems like you're using `hydra token user` as a substitute for your own application. This command is **just an example**. As noted in the docs, there are plenty of software libraries around that help you with oauth2: https://oauth.net/code/

**Comment by KishanRavindran** [comment] 2019-02-15 11:21
Hi @aeneasr I understand that this is not a bug or feature request I just need to know how can I change the callback url from 127.0.0.1:4446/callback to something of my own localhost when i try to change the callback url to locahost:4200 and when I run it and hit the 127.0.0.1:4446/callback it is not loading for me can you guide me on this.

**Comment by aeneasr** [comment] 2019-02-15 11:36
Not really, there's a lot of context missing. Make sure that:

1. Your client is allowed to use the redirect url `http://localhost:4200`
2. The oauth2 authorize url contains the right redirect url.

But again, this is all standard oauth2 stuff. Use a library for these things and most of your problems will go away.
