### ISSUE TITLE
Support multiple client secrets and secret rotation

### ISSUE THREAD

**Issue by sagarshah1983** [ory/hydra#3443] opened 2023-02-15 16:52 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

From security standpoint, we generally see a use-case where we may have to rotate client secret (regularly), but this brings in an impact to the client and force the client to start using new secret to avoid errors or downtime for their users.

In single sentence, I am proposing for a feature that can allow OIDC to authenticate client using new as well as old secret (for some time at least) giving enough time to the client to rotate password/secret used during authentication/authorization workflows.

I don't think, if we want to have a policy managing the rotation (that defines the timeframe for rotating secrets) also managed from within Hydra. That can still be managed outside of hydra.

### Describe your ideal solution

Ideal Solution would be to
- Support client authentication with new as well old secret.
- Old secret can be still considered valid for some timeframe (preferably configurable at client level).
- Retire old secret on demand using Admin API

### Workarounds or alternatives

Only option we have now is to notify the client that they need to enforce the password/secret change and implement that in their app

### Version

1.10.5

### Additional Context

This feature has been requested based on this original ticket #3005.

**Comment by zepatrik** [comment] 2023-09-06 15:09
Closing as duplicate of #1712

**Closed by zepatrik** 2023-09-06 15:09 UTC
Labels: feat
