### ISSUE TITLE
Tokens expire after 30 days even if ttl.refresh_token=-1

### ISSUE THREAD

**Issue by RazerM** [ory/hydra#2651] opened 2021-07-28 13:05 UTC
**Describe the bug**

I have configured hydra with `TTL_REFRESH_TOKEN=-1` and wanted to check the effect of this setting. Using hydra token introspection on a new refresh token returns an `exp` value 720h in the future (which is the default value for `TTL_REFRESH_TOKEN`. I checked that my configuration is picked up correctly by changing the value to 1h and seeing the effect on `exp`.

**Reproducing the bug**

1. Configure `TTL_REFRESH_TOKEN=-1`
2. Follow an authorization flow with `offline` scope to get a refresh token.
3. Use `hydra token introspect <refresh_token>`.
4. Observe that the expiry time is 720h in the future.

At least I hope that this is only an introspection bug and that the refresh token won't actually expire on that date..

_Server logs_

N/A

_Server configuration_

See above.

**Expected behavior**

I assume `exp` should be omitted if the refresh token doesn't expire? It's optional in RFC7662.

**Environment**

- Version: v1.10.3
- Environment: Debian

**Additional context**

**Comment by aeneasr** [comment] 2021-07-30 10:51
Hm, not sure where this is coming from. It would be very helpful if you have a code trace already figured out, or would be willing to supply a patch!

**Comment by littldr** [comment] 2021-08-12 12:16
@janz93 and I stumbled over the same issue. And it's not just for the token introspection. The refresh token really expires after 720h (default value).

After digging a bit in the code we found the following:

The lib used to parse the config [knadh/koanf](https://github.com/knadh/koanf) uses `time.ParseDuration` if the value of a duration field cannot be interpreted as integer or is zero or less. ([source](https://github.com/knadh/koanf/blob/v0.14.1/getters.go#L282)) This is the case if you specify `-1` in the config.

Now if you execute `time.ParseDuration("-1")` you will get a duration with the value `0` and the error `time: missing unit in duration "-1"`, but the error is ignored. We verified this with the following example: https://play.golang.org/p/P0nONl08kOx .

The actual issue now happens in [ory/fosite](https://github.com/ory/fosite/blob/c4ff105ec7c4c31811fbfa3674a50a47534a48e4/compose/config.go#L164). Here it checks if `RefreshTokenLifespan` equals zero (and that's now the case), if so it returns the default value (720h). In the end the rest of the code always get the default value and works then as expected.

We think - with our limited understanding of the overall architecture of hydra - that the easiest way of fixing this issue would be allowing to set `-1ns` as the ttl.  Running `time.ParseDuration("-1ns")` results in a duration with the value of `-1`, so the rest of the code should work.

But maybe @aeneasr has a better idea how to fix it? We would be happy to provide a patch. :)

**Comment by aeneasr** [comment] 2021-09-01 06:13
Whoops, looks like I forgot to hit that "comment" button. Thank you for the thorough investigation! That looks like a classical regression. Your analysis makes sense - setting `-1ns` or rather allowing a value `-1` by doing e.g. `koanf.GetInt()` before `GetDuration` would be the right approach!

**Comment by littldr** [comment] 2021-09-01 10:18
Thanks for your respone @aeneasr ! Allowing `-1` is maybe a more sustainable solution. Therefore I created a PR for knadh/koanf#104 .

But as it is an external lib, it may take some time until the PR is reviewed and merged.
So that's why I prepared a temporary workaround in ory/x#389. What do you think? Should we merge it or wait until `konaf` can be updated?

**Comment by knadh** [comment] 2021-09-01 10:57
> But as it is an external lib, it may take some time until the PR is reviewed and merged.

https://github.com/knadh/koanf/pull/104 is merged. Thanks for the fix.

**Comment by littldr** [comment] 2021-09-01 11:50
Thanks for the fast response @knadh ! :-)

I've created a PR to update `ory/x`. After that hydra can be updated and hopefully this issue will be solved. :-)

**Closed** 2021-09-07 14:26 UTC
Labels: bug
