### ISSUE TITLE
Hydra connect fails when the client secret contains "%"

### ISSUE THREAD

**Issue by gr-eg** [ory/hydra#631] opened 2017-10-25 11:04 UTC
Given a client with a secret of `secr%et`

Using `hydra connect` fails because [this line](https://github.com/ory/fosite/blob/c55d67903fdc5b2f4b200b663d4f1a0cb1d21dca/access_request_handler.go#L65) tries to unescape the secret but it contains an invalid escape sequence.

It looks like this is handled in the express consent app by [escaping the id and secret](https://github.com/ory/hydra-consent-app-express/commit/dbb5dbf01a4692a9554940ddccba3dc9c685fb01) but this isn't done with `hydra connect`

**Comment by arekkas** [comment] 2017-10-25 11:27
Ah yes, this should have been fixed with https://github.com/golang/oauth2/commit/13449ad91cb26cb47661c1b080790392170385fd and is probably not included here because the lock file is outdates. I'm currently working on a PR that will also replace glide with dep and I'll make sure to include this change as well.

Thank you for the report!

**Comment by gr-eg** [comment] 2018-01-16 10:42
It looks like this has potentially regressed in v0.10.10.

If a `%` is present in the client secret then `invalid_client` is raised from: https://github.com/ory/fosite/blob/master/access_request_handler.go#L87

I guess the problem is largely mitigated due to `%` not being present in the charset for secret generation but It's still possible to manually pass a failing secret via `hydra clients create`.

**Comment by arekkas** [comment] 2018-01-16 10:45
Hm, not sure, the client secret is being unescaped [here](https://github.com/ory/fosite/blob/master/access_request_handler.go#L109).

If your secret contains `%` (e.g. `foo%bar`) you should encode it so it becomes `%25` (e.g. `foo%25bar`)

**Comment by ruhavingfun22** [comment] 2018-01-16 17:51
Note I have also had problems with '%' and with '$'. This bit me pretty hard, as one of my deployments was using this as the root client credential. I spent a couple hours trying a lot of permutations of escaping my secrets for the root, as well as escaping when trying to call it from the CLI, before I eventually gave up on getting these two characters to work... Would be very interested if someone figured out the right combination of escaping to make this work.

**Comment by arekkas** [comment] 2018-01-16 19:39
@ruhavingfun22 did you manage to get it done? IMHO it should simply work with e.g. https://meyerweb.com/eric/tools/dencoder/

**Comment by ruhavingfun22** [comment] 2018-01-16 20:22
@arekkas I did not. I did try with the correct encodings from the site you mention, but something in the docker string parameterization, http request or how the DB was storing the special character didn't agree. I'm not saying it isn't possible to make it work, but after almost 2 hours of trying, it just wasn't worth the effort to make it work. All of the other special characters work without having to specify any encoding, so it was easier to just use those.

**Comment by arekkas** [comment] 2018-01-16 21:37
That sounds really frustrating, I'll take another look at this -> reopening

**Comment by emtammaru** [comment] 2018-05-17 20:13
This isn't technically a bug, because the RFC specifies that username & password should both be url-encoded (x-www-form-urlencoded) before base64 encoding them in the auth header:

https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by arekkas** [comment] 2018-05-20 09:01
`hydra connect` has been deprecated on master. If the issue persists with flag `--client-id` or env var `OAUTH2_CLIENT_ID` let me know

**Closed by arekkas** 2018-05-20 09:01 UTC
Labels: bug, upstream

**Comment by wojciechce** [comment] 2018-08-23 10:00
Hi there.
Seems like the problem mentioned in this issue is still valid. We are looking forward to hearing your opinion on that. Thank you in advance!

Summary:
Special characters like '%Q', '%n' in client_secret are causing Hydra returns 400.

Steps to reproduce:
1. Follow the [5 minute tutorial](https://www.ory.sh/docs/guides/master/hydra/1-tutorial/)
2. Create a client with password containing '%Q' or '%n':
```
docker exec -it hydra_hydra_1 \
    hydra clients create \
    --endpoint http://localhost:4445 \
    --id percent-sign-client \
    --secret 'foo%Qbar' \
    --grant-types authorization_code,refresh_token \
    --response-types code,id_token \
    --scope openid,offline \
    --callbacks http://127.0.0.1:5555/callback
```
3. Setup home route on http://127.0.0.1:5555/ (tutorial)
4. Open http://127.0.0.1:5555/ in your browser.
5. Stop serving home route by pressing CTRL+C.
6. Authenticate, login and when your browser served an error, copy 'code' from params of URL.
7. Prepare POST request, replace {{code}} with code from URL:
```
POST /oauth2/token HTTP/1.1
Host: localhost:4444
Authorization: Basic cGVyY2VudC1zaWduLWNsaWVudDpmb28lUWJhcg==
Cache-Control: no-cache
Content-Disposition: form-data; name="grant_type" authorization_code
Content-Disposition: form-data; name="code" {{code}}
Content-Disposition: form-data; name="redirect_uri" http://127.0.0.1:5555/callback
Content-Disposition: form-data; name="refresh_token"
```
8. Execute request.
9. Hydra responds with error:
```
{
    "error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed",
    "error_hint": "The client secret in the HTTP authorization header could not be decoded from \"application/x-www-form-urlencoded\".",
    "status_code": 400,
    "error_debug": "invalid URL escape \"%Qb\""
}
```

**Comment by aeneasr** [comment] 2018-08-23 10:06
`base64decode("cGVyY2VudC1zaWduLWNsaWVudDpmb28lUWJhcg==")` is `percent-sign-client:foo%Qbar` but should be `urlencode("percent-sign-client:foo%Qbar")` which is `percent-sign-client%3Afoo%25Qbar` and would be base64encoded `cGVyY2VudC1zaWduLWNsaWVudCUzQWZvbyUyNVFiYXI=`. See [here](https://tools.ietf.org/html/rfc6749#section-2.3.1) for spec.

**Comment by michalwojciechowski** [comment] 2018-08-23 11:05
@aeneasr please confirm if my understanding is correct:
https://tools.ietf.org/html/rfc6749#appendix-B assumes that our credentials represent a valid octet sequence and treats all percentage sings as the special unicode signs (followed by other characters). Since this is not always true, we need to escape all special characters with e.g. `urlencode`.

**Comment by aeneasr** [comment] 2018-08-23 11:07
Yes! I've worked on PRs for JS and Go OAuth2 libraries that got that wrong. Using special chars like `%` is uncommon for OAuth2 so most have not encountered this before. My recommendation is to skip these special chars and only have url-safe chars. This will avoid issues with other libraries that get this wrong.

**Comment by wojciechce** [comment] 2018-08-23 11:32
@aeneasr 
As u wrote above, I created new client:
```
docker exec -it hydra_hydra_1 \
    hydra clients create \
    --endpoint http://localhost:4445 \
    --id percent-sign-client \
    --secret 'foo%Qbar' \
    --grant-types authorization_code,refresh_token \
    --response-types code,id_token \
    --scope openid,offline \
    --callbacks http://127.0.0.1:5555/callback
```
Then I extecuted request:
```
POST /oauth2/token HTTP/1.1
Host: localhost:4444
Authorization: Basic cGVyY2VudC1zaWduLWNsaWVudCUzQWZvbyUyNVFiYXI=
Cache-Control: no-cache

Content-Disposition: form-data; name="grant_type" authorization_code
Content-Disposition: form-data; name="code" {{code}}
Content-Disposition: form-data; name="redirect_uri" http://127.0.0.1:5555/callback
Content-Disposition: form-data; name="refresh_token"
```
And then Hydra returns:
```
{
    "error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed",
    "error_hint": "Client credentials missing or malformed in both HTTP Authorization header and HTTP POST body.",
    "status_code": 400
}
```
Please confirm that is correct Hydra behaviour or I did something wrong.

**Comment by michalwojciechowski** [comment] 2018-08-23 11:33
Thank you! Wasn't aware that this is such a big deal in OAuth world. We will definitely take your recommendation into account, perhaps this is the most convenient way for everyone. 

And the follow up question is: we've tried out your suggestion to `urlencode` and `base64` our credentials, and the flow moved to the point where Hydra rejects invalid credentials, no matter if `--secret 'foo%Qbar' ` or `--secret 'foo%25Qbar' ` was used during the creation of the client. Can you please advice?

**Comment by wojciechce** [comment] 2018-08-23 12:35
It works! Great!
I confirm. Solution is `base64(urlencode(username):urlencode(password))`.

@aeneasr Thank you for your time.

**Comment by aeneasr** [comment] 2018-08-23 12:38
No problem :)
