### ISSUE TITLE
HTTP Exposure does not work

### ISSUE THREAD

**Issue by akrause-cel** [ory/hydra#3044] opened 2022-03-24 08:25 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The command `hydra serve all --dangerous-force-http` does not have an effect anymore. Hydra still serves TLS endpoint.

### Reproducing the bug

Run `hydra serve all --dangerous-force-http` and call any endpoint (admin/client) with http

### Relevant log output

```shell
time=2022-03-24T09:23:41+01:00 level=info msg=Setting up http server on :4444 audience=application service_name=Ory Hydra service_version=master
time=2022-03-24T09:23:42+01:00 level=info msg=Setting up http server on :4445 audience=application service_name=Ory Hydra service_version=master
2022/03/24 09:24:10 http: TLS handshake error from [::1]:59521: EOF
```

### Relevant configuration

```yml
N/A
```

### Version

master

### On which operating system are you observing this issue?

macOS

### Additional Context

Worked with previous version

**Comment by aeneasr** [comment] 2022-03-24 11:32
If that were the case, all tests would fail and everything would be deep-red as we use this to circumvent any HTTPS requirements in e2e tests and functional tests. Are you sure there wasn't maybe another instance of hydra running locally?

**Comment by akrause-cel** [comment] 2022-03-24 11:45
I am pretty sure. I even saw the flag in the debugger and and the check returned false. 

Going back to this fork ist works: https://github.com/akrause-cel/hydra/tree/a500b16a45736844bb5bb79332103869a0f22497

**Comment by akrause-cel** [comment] 2022-03-24 11:58
This one returns false: https://github.com/ory/hydra/blob/e3236dd9f6febbb2c147417f6c21a7285418e055/driver/config/tls.go#L72

here is my launch config:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "./main.go",
            "args": ["serve", "all", "--dangerous-force-http"],
            "env": {
                "DSN": "memory"
            },
            "buildFlags": "-tags=sqlite"
        }
    ]
} 
```

**Comment by aeneasr** [comment] 2022-03-24 13:21
Thank you for the reproducible case, it appears this recently broke with an upgrade of ory/x: https://github.com/ory/hydra/compare/v1.11.7...master#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R51

@zepatrik I believe you changed something in the flag logic, could this be a regression?

I'm not sure how e2e tests pass currently, we explicitly use the `--dangerous-force-http`

**Comment by aeneasr** [comment] 2022-03-24 13:26
Yeah, looks like e2e are not passing at all on master right now

**Comment by aeneasr** [comment] 2022-03-24 13:49
The problem was two-fold:

1. Regression introduced in ory/x
2. CI using a cached build thus not catching the error

We would probably have noticed this when something in Hydra changed that required an e2e update :/

**Comment by aeneasr** [comment] 2022-03-24 16:22
fixed via https://github.com/ory/hydra/pull/3046

**Closed by aeneasr** 2022-03-24 16:22 UTC
Labels: bug
