### ISSUE TITLE
JWT Bearer Assertion Grant not usable to propagate Principal 

### ISSUE THREAD

**Issue by akrause-cel** [ory/hydra#3011] opened 2022-02-24 10:34 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

As described in the [OAuth2 JWT Bearer Grant Type Validation](https://www.ory.sh/docs/hydra/guides/oauth2-grant-type-jwt-bearer#oauth2-jwt-bearer-grant-type-validation) documentation, the subject field of an assertion token must match the subject registered in the trust relationship. This means that I have to establish a trust relationship per subject/issuer/jwk. Which can lead to an unnecessary and complex to maintain proliferation of trusts. As far as I understand the grant described in [rfc7523 section 2.1](https://datatracker.ietf.org/doc/html/rfc7523#section-2.1) is meant to enable a combination of principal propagation and authorization delegation. The current implementation effectively blocs the pincipal propagation intension.

### Describe your ideal solution

Ideally the following need is removed:

The JWT MUST contain a sub (subject) claim identifying the principal that is the subject of the JWT (e.g. user ID). The value must match the subject value of the trust relationship.

The `/trust/grants/jwt-bearer/issuers` API Endpoint (POST) makes the `subject`field optional.

The following code lines are stripped from subject references:
[https://github.com/ory/fosite/blob/749000d58d96a1cdaa361fc4808ef6649c79b89f/handler/rfc7523/handler.go#L216](https://github.com/ory/fosite/blob/749000d58d96a1cdaa361fc4808ef6649c79b89f/handler/rfc7523/handler.go#L216)
[https://github.com/ory/fosite/blob/749000d58d96a1cdaa361fc4808ef6649c79b89f/handler/rfc7523/handler.go#L223](https://github.com/ory/fosite/blob/749000d58d96a1cdaa361fc4808ef6649c79b89f/handler/rfc7523/handler.go#L223)
 

### Workarounds or alternatives

Currently the only alternative is to establish a trust relationship per subject/issuer/jwk combination which is prohibitively complex.

### Version

v.1.11

**Comment by aeneasr** [comment] 2022-02-24 11:37
Is this a dupe of https://github.com/ory/hydra/issues/2930#issuecomment-1047709327 ?

**Comment by akrause-cel** [comment] 2022-02-24 12:01
> Is this a dupe of [#2930 (comment)](https://github.com/ory/hydra/issues/2930#issuecomment-1047709327) ?

yes, this is a duplicate

**Closed** 2022-02-24 12:06 UTC
Labels: feat
