### ISSUE TITLE
Getting issue while setting up with azure adb2c sso and expo build

### ISSUE THREAD

**Issue by RajanRV** [ory/hydra#2881] opened 2021-12-04 08:00 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

We're trying to reconfigure the ory hydra with azure adb2c sso, but we're not able to configure it as we are new to this.

sharing the configuration we've done for the hydra + azure b2c

domain information:
hydra public endpoint: hydra.fbn3.com
hydra private (admin) endpoint: hydra-admin.fbn3.com
consent node endpoint: auth.fbn3.com

We're using this configuration in Expo code (React Native):
`
import { makeRedirectUri, ResponseType } from "expo-auth-session";
import { exchangeCodeAsync, useAuthRequest } from "expo-auth-session";
import * as WebBrowser from "expo-web-browser";

WebBrowser.maybeCompleteAuthSession();

export const discovery = {
authorizationEndpoint: "https://hydra.fbn3.com/oauth2/auth",
tokenEndpoint: "https://hydra.fbn3.com/oauth2/token",
revocationEndpoint: "https://hydra.fbn3.com/oauth2/revoke",
};

export const config = {
responseType: ResponseType.Code,
clientId: clientId,
scopes: scopes,
// For usage in managed apps using the proxy
redirectUri: makeRedirectUri({ useProxy: true }),
usePKCE: false,
};

let [request, response, promptAsync] = useAuthRequest(
{
...config,
},
discovery
);

function authenticate() {
console.log("AUTHENTICATED!");
setAuthenticated(true);
}

async function login() {
setLoginStarted(true);
const result = await promptAsync({ useProxy: true });
console.log("result from prompt", result);
}

useEffect(() => {
login();
}, [])

useEffect(() => {
if (response?.type === "success") {
const { code } = response.params;
const auth = await exchangeCodeAsync(
{
code: code,
redirectUri: redirectUri(),
clientId: clientId,
scopes: scopes,
},
discovery
);
await cacheAuthAsync(auth);
setAccessToken(auth.accessToken);
}
}, [request, response])

return (
<View
style={{
height: "100%",
backgroundColor: "#33CA8F",
}}
>

);

`

These are the commands we've used for the hydra image creation in kubernetes. (note: postgresql is already configured)
`
helm install hydra 
--set 'hydra.config.secrets.system={'$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | base64 | head -c 32)'}' 
--set 'hydra.config.dsn=postgres://user:password@postgres-postgresql:5432/hydra?sslmode=disable' 
--set 'hydra.config.urls.self.issuer=https://hydra.fbn3.com/' 
--set 'hydra.config.urls.login=https://auth.fbn3.com/login' 
--set 'hydra.config.urls.consent=https://auth.fbn3.com/consent' 
--set 'hydra.autoMigrate=true' 
ory/hydra --version 0.21.1

hydra clients create 
--endpoint https://hydra-admin.fbn3.com 
--id fbn3staging 
--scope openid,offline,email,profile 
--secret secret 
--callbacks https://auth.fbn3.com/callback 
-g client_credentials
`

using this config we're getting invalid configuration error while trying to logging in.
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect

### Reproducing the bug

Follow the steps mentioned in the description.

### Version

0.21.1

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment] 2021-12-06 17:37
Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:

```
$ make format
$ git commit -a -m "styles: format code"
$ git push
```

Thank you!

**Comment by aeneasr** [comment] 2021-12-06 17:37
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment.

If you have used an issue template and see this comment, it means that your description lacks information that allows maintainers to understand what problem you are facing and how to reproduce it.

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed. Thank you for your understanding!

**Comment by RajanRV** [comment] 2021-12-08 15:45
That previous issue looks fixed as we're now able to see the login screen in the app, but now we're facing 401 auth error while requesting new auth token from the hydra server that request is being done to the token endpoint specified in the discovery configuration (https://hydra.fbn3.com/oauth2/token).

Can someone help us to fix that, we can hire the person to be constant for setting up the hydra correctly.

**Closed** 2022-06-24 16:45 UTC
Labels: bug
