### ISSUE TITLE
Hydra Migration issues with MySQL database as DSN

### ISSUE THREAD

**Issue by zecarlos94** [ory/hydra#3149] opened 2022-06-13 16:53 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Using a MySQL database as DSN, Ory Hydra logs `Successfully applied migrations!` despite stopping its execution after throwing `Error 1065: query was empty` on `initial_sqlite` step which leads to invalid schemas on generated tables:

`hydra_oauth2_authentication_request_handled` table -> missing `column amr [text]`

`hydra_client` table -> missing column  `registration_access_token_signature [varchar(128)]`

`hydra_oauth2_consent_request` table -> missing column `amr [text]`

`hydra_oauth2_trusted_jwt_bearer_issuer` table -> missing entire table that is supposed to have the following columns,

`id uuid`
`issuer varchar(255)`
`subject varchar(255)`
`scope text`
`key_set varchar(255)`
`key_id varchar(255)`
`created_at timestamp`
`expires_at timestamp`

These differences were obtained by comparing generated schemas after respective migrations using a MySQL database as DSN (the ones with reported issues) with generated schemas after respective migrations using a PostgreSQL database as DSN

### Reproducing the bug

MySQL database used as Hydra's DSN is a Vitess MySQL database (https://vitess.io/) version 8.0.23
Hydra version v1.11.7 

Both MySQL and Ory Hydra are deployed via Terraform/Kubernetes to a Google Cloud Platform environment.
Hydra Migrations run on 'init_container' (with command `hydra migrate sql --read-from-env --yes --config /etc/config/hydra.yml`) before instantiating hydra 'container' (with command `hydra serve all --config /etc/config/hydra.yml`)

Create new pod of ory hydra deployment and check generated schemas and hydra migrator logs.

When creating a new OAuth2 client (POST /clients) the request fails because column `registration_access_token_signature` does not exist.

### Relevant log output

```shell
20200819163013000000 add_client_id_subject_idx_to_access_and_refresh Applied
20200913192340000000 initial_sqlite Pending
20201110104000000000 drop_uq_oauth2 Pending
20201116133000000000 set_null_time Pending
20210928155900000000 support_amr_claim Pending
20211226155900000000 grant_jwk_bearer Pending
20211226156000000000 dynamic_registration Pending
Could not apply migrations:
Error 1065: query was empty
error executing migrations/20200913192340000000_initial_sqlite.up.sql, sql: -- this migration is only for sqlite
{}
github.com/ory/x/popx.NewMigrationBox.func1.1
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migration_box.go:71
github.com/ory/x/popx.Migration.Run
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migration_info.go:34
github.com/ory/x/popx.(*Migrator).UpTo.func1.2
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migrator.go:139
github.com/ory/x/popx.(*Migrator).isolatedTransaction
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migrator.go:314
github.com/ory/x/popx.(*Migrator).UpTo.func1
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migrator.go:138
github.com/ory/x/popx.(*Migrator).exec
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migrator.go:559
github.com/ory/x/popx.(*Migrator).UpTo
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migrator.go:92
github.com/ory/x/popx.(*Migrator).Up
 /go/pkg/mod/github.com/ory/x@v0.0.344/popx/migrator.go:80
github.com/ory/hydra/persistence/sql.(*Persister).MigrateUp
 /project/persistence/sql/persister_migration.go:40
github.com/ory/hydra/cmd/cli.(*MigrateHandler).MigrateSQL
 /project/cmd/cli/handler_migrate.go:107
github.com/spf13/cobra.(*Command).execute
 /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
 /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
 /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/ory/hydra/cmd.Execute
 /project/cmd/root.go:87
main.main
 /project/main.go:33
runtime.main
 /usr/local/go/src/runtime/proc.go:255
runtime.goexit
 /usr/local/go/src/runtime/asm_amd64.s:1581
Successfully applied migrations!
Thank you for using Ory Hydra v1.11.7!
```

### Version

v1.11.7 

### In which environment are you deploying?

Kubernetes

**Comment by aeneasr** [comment] 2022-06-13 17:47
Would it be possible to provide a reproducible set up in Docker Compose to quickly try out and identify what the problem is? It looks like there is an issue in the detection of the database type as it's trying to execute SQL migrations.

**Comment by zecarlos94** [comment] 2022-06-20 14:26
Hi aeneasr,

Thanks for reaching out. Hope that we can fix this issue.

`docker-compose.yml` file as requested, 

```version: '3.7'
services:
  vttestserver:
    container_name: vitess-mysql80
    image: vitess/vttestserver:mysql80
    environment:
      - PORT=33574
      - PLANNER_VERSION=gen4fallback 
      - KEYSPACES=test,unsharded
      - NUM_SHARDS=2,1 
      - MYSQL_MAX_CONNECTIONS=70000 
      - MYSQL_BIND_HOST=0.0.0.0 
    healthcheck:
      test: mysqladmin ping -h127.0.0.1 -P33577
      interval: 5s
      retries: 5
      timeout: 2s
    ports:
      - '33577:33577'

  hydra-migrate:
    container_name: vitess-mysql80-hydra-migrate
    command: migrate sql -e --yes -c /etc/config/hydra/hydra.yaml
    depends_on:
      - vttestserver
    image: oryd/hydra:v1.11.7
    environment:
      - DSN=mysql://root:password@tcp(vttestserver:33577)/unsharded?parseTime=true
    restart: on-failure
    volumes:
      - type: bind
        source: ./configs/hydra
        target: /etc/config/hydra

  hydra:
    container_name: vitess-mysql80-hydra
    command: serve all --dangerous-force-http -c /etc/config/hydra/hydra.yaml
    depends_on:
      - hydra-migrate
    environment:
      - DSN=mysql://root:password@tcp(vttestserver:33577)/unsharded?parseTime=true
    image: oryd/hydra:v1.11.7
    ports:
      - '4444:4444'
      - '4445:4445'
      - '5555:5555'
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./configs/hydra
        target: /etc/config/hydra
```
and ` hydra.yaml` config file,   
```
  log:
  format: json
  level: debug

oauth2:
  expose_internal_errors: true

oidc:
  subject_identifiers:
    pairwise:
      salt: 8Lqr7vAXa2252nn1lpagghqQ=
    supported_types:
      - pairwise
      - public

secrets:
  system:
    - 8Lqr7vAXa2252nn1lpagghqQ=

serve:
  cookies:
    same_site_mode: Lax

  admin:
    cors:
      allow_credentials: true
      allowed_headers:
        - '*'
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
        - OPTIONS
        - TRACE
      allowed_origins:
        - '*'
      enabled: true
  public:
    cors:
      allow_credentials: true
      allowed_headers:
        - '*'
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
        - OPTIONS
        - TRACE
      allowed_origins:
        - '*'
      enabled: true

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout
```

**Comment by aeneasr** [comment] 2022-06-23 08:03
Thank you! I can reproduce this issue. Looks like the problem is that Vitess is returning an error when an empty query is being executed, which is not the case for any other of our supported databases. To fix it, we would need to handle the vitess error in this method:

https://github.com/ory/x/blob/a8573c8fcc3ea212ac63fe9803849fe4728644e5/popx/migration_box.go#L143-L149

In the end, the problem is also that the referenced migration consist only of a single comment but because of that, it is not handled by this

https://github.com/ory/x/blob/a8573c8fcc3ea212ac63fe9803849fe4728644e5/popx/migration_box.go#L143

because the file is not empty, it just doesn't have any SQL statements. 

Here is a PR which fixes that: https://github.com/ory/x/compare/fix-hydra-3149?expand=1

We are planning one more release before the v2.0 release and it might be possible that the fix will land in that v1 branch still but it might also not depending on the complexity of including this change.

If you can fix Vitess to not return such an error, I think you could hotfix the problem. Another possibility is to trick the migrator into thinking that the migration has already been applied by inserting the ID `20200913192340000000` manually in the schema_migrations table so that the migrator thinks that the migration has been applied. This is ok because the migration is empty!

**Comment by zecarlos94** [comment] 2022-06-23 08:50
Hi @aeneasr 
Thank you so much for this analysis and its respective fix
Awesome dev support 👍

**Comment by aeneasr** [comment] 2022-06-23 09:22
You're welcome :)

**Comment by aeneasr** [comment] 2022-06-24 15:46
I'm closing this issue. It has not been resolved on master yet, but it is fixed on v2.x and a hotfix is also available as per my comment above.

**Closed by aeneasr** 2022-06-24 15:46 UTC
Labels: bug
