### ISSUE TITLE
Generate JWK with “dp” (First Factor CRT Exp) , “dq” (Second Factor CRT Exp) , “qi” (First CRT Coefficient) Parameter

### ISSUE THREAD

**Issue by emilesalem** [ory/hydra#3068] opened 2022-04-13 19:37 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

This is following the same need as outlined here: https://github.com/ory/hydra/discussions/3008

### Describe your ideal solution

generate JWKs that include  
“dp” (First Factor CRT Exponent) Parameter
“dq” (Second Factor CRT Exponent) Parameter
“qi” (First CRT Coefficient) Parameter

### Workarounds or alternatives

calculate these values from the client

### Version

v1.11.7

**Comment by aeneasr** [comment] 2022-04-14 19:46
Unfortunately the library we use (go-jwt) does not generate these values. As far as I understand, these values are optional and save the consumer a bit of computation by being pre-computed, but can easily be derived from the other keys.

This might be resolved by moving to a different JWK library which we have plans for, but do not have it as a high priority. If my assumption here is correct, I'd track this issue as a duplicate of: https://github.com/ory/hydra/issues/1825

**Comment by aeneasr** [comment] 2022-04-16 21:24
Closing as per my comment above but feel free to comment or reopen if you feel there's more to this :)

**Closed by aeneasr** 2022-04-16 21:24 UTC
Labels: feat
