### ISSUE TITLE
Email claim not present on ID token after issuing with refresh

### ISSUE THREAD

**Issue by 3schwartz** [ory/hydra#3852] opened 2024-09-30 11:01 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

## Issue
- ID token doesn’t have the `email` (and `sid`) claim after issuing using refresh token
- Access token doesn’t have the email claim when using scope `email`. It is only on the ID token.

## Details

We are using the `oidc-client-ts` (v 3.0.1) client in our frontend with the authorization code flow and refresh tokens, https://www.ory.sh/docs/oauth2-oidc/refresh-token-grant.

We have enabled the `openid `, `email` and `offline_access` scope in the OAuth2 Client used.

Our client setup are using `oidc-client-ts`:
```
new UserManager({
      authority: 'http://localhost:4000’, // ory channel in this example
      redirect_uri: window.location.origin + '/auth/callback',
      client_id: "<SOME_ID_CLIENT>",
      response_type: 'code',
      scope: 'openid email offline_access',
      automaticSilentRenew: true,
      post_logout_redirect_uri: window.location.origin + '/auth/login',
      extraQueryParams: {
        audience: 'http://<SOME_DOMAIN>.com'
      }
})
```

The first request to our token endpoint after a successfully login is using our authorization code. We call `https://<OUR_DOMAIN>.com/oauth2/token` with the form data
```
grant_type: authorization_code
redirect_uri: https://<OUR_DOMAIN>.com/auth/callback
code: <SOME_CODE>
code_verifier: <SOME_VERIFIER>
client_id: <SOME_CLIENT_ID>
```
and we get response

```
{
    "access_token": “<ACCESS_TOKEN>",
    "expires_in": 86399,
    "id_token”: “<ID_TOKEN>",
    "refresh_token": “<REFRESH_TOKEN>",
    "scope": "openid email offline_access",
    "token_type": "bearer"
}
```

Now the `email` claim is present in the id token but not in the access token.

Access token
```
{
  "aud": [
    "http://<SOME_DOMAIN>.com"
  ],
  "client_id": "<SOME_CLIENT_ID>",
  "exp": 1727779067,
  "ext": {},
  "iat": <iat>,
  "iss": "https://<PROJECT_SLUG>.projects.oryapis.com",
  "jti": “<jti>",
  "nbf": <nbf>,
  "scope": "openid email offline_access",
  "sub": “<sub>"
}
```

ID token
```
{
  "amr": [
    "password",
    "password",
    "password",
    "password",
    "password",
    "password",
    "password",
    "password",
    "password"
  ],
  "at_hash": “<AT_HASH>",
  "aud": [
    “<AUD>"
  ],
  "auth_time": 1727692664,
  "email": “<USER_EMAIL>",
  "email_verified": true,
  "exp": 1727779067,
  "iat": <IAT>,
  "iss": "https://<PROJECT_SLUG>.projects.oryapis.com",
  "jti": “<jit>",
  "rat": <rat>,
  "sid": “<SID>",
  "sub": “<sub>"
}
```

Now after we use our refresh token we call the token endpoint again `https://<OUR_DOMAIN>.com/oauth2/token` with body
```
grant_type: refresh_token
refresh_token: <REFRESH_TOKEN>
scope: openid email offline_access
client_id: <CLIENT_ID>
```

we get response
```
{
    "access_token”: “<ACCESS_TOKEN>",
    "expires_in": 30,
    "id_token”: “<ID_TOKEN>",
    "refresh_token": “<REFRESH_TOKEN>",
    "scope": "openid email offline_access",
    "token_type": "bearer"
}
```

where access token contains
```
{
  "aud": [
    "http://<SOME_DOMAIN>.com"
  ],
  "client_id": "<SOME_CLIENT_ID>",
  "exp": 1727779067,
  "ext": {},
  "iat": <iat>,
  "iss": "https://<PROJECT_SLUG>.projects.oryapis.com",
  "jti": “<jti>",
  "nbf": <nbf>,
  "scope": "openid email offline_access",
  "sub": “<sub>"
}
```

and ID token now doesn’t have the `email` and `sid` claim
```
{
  "amr": [
    "password",
    "password",
    "password",
    "password",
    "password",
    "password",
    "password",
    "password",
    "password"
  ],
  "at_hash": “<AT_HASH>",
  "aud": [
    “<AUD>"
  ],
  "auth_time": 1727692664,
  "email": “<USER_EMAIL>",
  "email_verified": true,
  "exp": 1727779067,
  "iat": <IAT>,
  "iss": "https://<PROJECT_SLUG>.projects.oryapis.com",
  "jti": “<jit>",
  "rat": <rat>,
  "sub": “<sub>"
}
```

### Reproducing the bug

- Create a OIDC client with scopes `openid email offline_access`
- Login and validate email claim present on ID token after calling /auth/token using access code, but not on the access token
- Use refresh token and now the email (and `sid`) claim are missing from the ID token. Still missing on the access token

### Version

Using Ory network

### On which operating system are you observing this issue?

Ory Network

### In which environment are you deploying?

None

**Comment by aeneasr** [comment] 2024-10-13 09:44
I'm a bit confused, in the section

> and ID token now doesn’t have the email and sid claim

you show a JWT token that does have the email claim. It is missing the sid claim though!

**Comment by aeneasr** [comment] 2024-10-13 10:11
So, I have tried to reproduce this issue both with the flag set to true and to false, however, I always get the same claims in the ID token from the refresh_token grant as I do from the original grant (email and sid). Therefore, I assume that this is some other issue and am closing this as can't reproduce. Please feel free to provide more details/context in case you find this issue again.

**Closed by aeneasr** 2024-10-13 10:11 UTC
Labels: bug

**Comment by 3schwartz** [comment] 2024-10-14 07:18
> I'm a bit confused, in the section
> 
> > and ID token now doesn’t have the email and sid claim
> 
> you show a JWT token that does have the email claim. It is missing the sid claim though!

Sorry it was a copy paste error.

**Comment by 3schwartz** [comment] 2024-10-14 07:20
> So, I have tried to reproduce this issue both with the flag set to true and to false, however, I always get the same claims in the ID token from the refresh_token grant as I do from the original grant (email and sid). Therefore, I assume that this is some other issue and am closing this as can't reproduce. Please feel free to provide more details/context in case you find this issue again.

I have compared both identity and oauth2 configuration and this one change is the only difference between the project where I have issues, and the new project which works.

Could you maybe help provide some links to documentation or give some details what this flags does in the backend `use_continue_with_transitions: true`?

**Comment by 3schwartz** [comment] 2024-10-25 14:51
@aeneasr I’ve gained additional insights into the issue.

It appears that the problem arises specifically when we enable a token webhook, as described in the documentation here: [Token Claims at Refresh](https://www.ory.sh/docs/hydra/guides/claims-at-refresh).

During the first call to the token webhook endpoint, the email claim is correctly included in the token. However, when the webhook is triggered with the refresh_token grant type, the email claim is missing.

Interestingly, if we disable the webhook, the email claim consistently appears as expected. We’re able to replicate this issue reliably by toggling the webhook on and off.
