### ISSUE TITLE
DELETE login/{user} and  DELETE consent/{user} can not redirect to Login page

### ISSUE THREAD

**Issue by liguobao** [ory/hydra#1035] opened 2018-09-15 13:51 UTC
Do you want to request a feature or report a bug?
bug

What is the current behavior?
DELETE login/{user} and DELETE consent/{user} can not redirect to Login page

Click here to show Hydra Traceback
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

We DELETE login/{user} and  DELETE consent/{user} for some user.
```
DELETE
/oauth2/auth/sessions/consent/{user}
Revokes all previous consent sessions of a user

DELETE
/oauth2/auth/sessions/login/{user}
Invalidates a user's authentication session

```
but we found if user login,that will  redirect to client callback page and fail.

What is the expected behavior?

Hydra responds with []

Which version of the software is affected?

1.0 beta 7

**Comment by aeneasr** [comment] 2018-09-15 13:55
Please use the provided issue template to describe your problem.

**Comment by liguobao** [comment] 2018-09-15 14:01
> Please use the provided issue template to describe your problem.

So sorry,I  had updated.

**Comment by aeneasr** [comment] 2018-09-15 14:04
Please update to the latest version (beta.9) and see if the problem persists. If it does, provide meaningful ways for reproducing the problem. For example:

```
$ DATABASE_URL=memory hydra serve all --dangerous-force-http
$ hydra token user ...
```

```
$ curl -X DELETE ....
```

And give some details about the error you're experiencing (client callback page fails is nothing I can work with). Thank you!

**Comment by aeneasr** [comment] 2018-09-15 16:31
Not sure what's going on there but the URL you posted returns a 404 (https://test-oauth.****.org/clients) so it's either misconfigured or whatever, but it's definitely not a bug with hydra. Maybe someone in the chat can help you, but I'm going to closing this because it has to do with your deployment / setup and not the project itself.

**Closed by aeneasr** 2018-09-15 16:31 UTC

**Comment by liguobao** [comment] 2018-09-15 16:43
on beta.7 ,hydra log like that:
```
time="2018-09-15T16:36:40Z" level=info msg="started handling request" method=GET remote=114.91.68.137 request=/clients request_id=90a119bd266a8af73e9b1cc352b0752c
time="2018-09-15T16:36:40Z" level=info msg="completed handling request" measure#https://mydomain.com
 latency=2505374 method=GET remote=114.91.68.137 request=/clients request_id=90a119bd266a8af73e9b1cc352b0752c status=200 text_status=OK took=2.505374ms

```
on beta.9 ,hydra log like that:
```

time="2018-09-15T16:33:54Z" level=info msg="started handling request" method=GET remote=114.91.68.137 request=/clients request_id=953081257a40206153e800d04a53da94
time="2018-09-15T16:33:54Z" level=info msg="completed handling request" measure#https://mydomain.com .latency=102896 method=GET remote=114.91.68.137 request=/clients request_id=953081257a40206153e800d04a53da94 status=404 text_status="Not Found" took="102.896µs"
```

@aeneasr
